### ISSUE TITLE
change repository.provider.quasar to repository.providers.quasar in addons.xml

### ISSUE THREAD

**Issue by compyy** [mancuniancol/repository.providers.quasar#2]
change repository.provider.quasar to repository.providers.quasar in addons.xml

**Comment by mancuniancol** [comment]
Thank you for the feedback.  I was having trouble for that, but I didn't see the error before.

**Comment by compyy** [comment]
Hi Thanks, 
but http://offshoregit.com/pulsarunofficial/raw/master/addons.xml needs to be updated as well, it is still using invalid folder name. 
Regards, Yasir Ashfaque

**Comment by mancuniancol** [comment]
I am not the administrator of the repo. When, I do a modification, I send the demand and it takes couples hours sometimes more to be updated. If you don't see the new version yet. It means that it is still in process. Besides, that repo has a several mirrors to be updated.
