### ISSUE TITLE
script.subscription.quasar.trakt not working

### ISSUE THREAD

**Issue by vdutch** [mancuniancol/repository.providers.quasar#3]
script.subscription.quasar.trakt can't create the .strm files in tvshows, and in movies it creates the .strm files but they cannot be opened, i get this error on the log: 5511.539062 T:1946464256   ERROR: Unable to find plugin plugin.video.pulsar
01:54:28 85511.539062 T:1946464256   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.pulsar/movie/plugin://plugin.video.quasar/movie/tt2024544/links]

if you need any extra info please ask
Thanks

**Comment by mancuniancol** [comment]
Yes, I would like to have your log in mode debug. You can use pastebin.com to share it

**Comment by vdutch** [comment]
The file exceeded the maximum file size in free pastebin accounts so i've uploaded it to my meocloud: https://meocloud.pt/link/a9dd2d03-4829-4bcb-955f-f6fb1441ef15/kodi.log/

**Comment by mancuniancol** [comment]
Ok. I've fixed the problem it was a bug in the service.  I will close this issue.

https://github.com/mancuniancol/script.subscription.quasar.trakt/releases/tag/v1.0.2

**Comment by vdutch** [comment]
Thanks, i made a test with the source code zip you provided but i got the same errors, i will try again when the zip gets updated in the repositorys

**Comment by mancuniancol** [comment]
Could you confirm if you have mctools v1. 3.5?
https://github.com/mancuniancol/script.module.mctools/archive/v1.3.5.zip

**Comment by vdutch** [comment]
That seems to be the problem, i'm on mc tools v1.3.3.in all my systems... i've just installed v1.3.5 and i'm importing my collection again to see if it works, i'll report asap. By the way, any idea why mc tools didn't update in any of my systems?

**Comment by vdutch** [comment]
After updating to mctools v1.3.5 and rebuilding my database all seems to be running smooth. Thanks

**Comment by mancuniancol** [comment]
Good. I will close this issue then.
